apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: contosoair  
spec:
  location: eastus
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: DatabaseAccount
metadata:
  name: contosoairdbaccount  
spec:
  location: eastus
  owner:
    name: contosoair
  kind: MongoDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: eastus